/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.*;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static int[] roll(int n) {
        int random = (int) (Math.random() * (6 - 1 + 1) + 1);
        int[] rollingResults=new int[n];
        for (int i = 0; i < n; i++) {
            rollingResults[i]=random;
            System.out.println(rollingResults[i]);
            random = (int) (Math.random() * (6 - 1 + 1) + 1);
        }
        return rollingResults;
    }
    public static boolean  containsDuplicates(int[] array){
        boolean flag = false;
        for(int i = 0; i < array.length; i++){
            for(int j = i+1; j < array.length; j++){
                if (array[j] == array[i]){
                    flag = true;
                    System.out.println(flag);
                    return flag;
                }
            }
        }
        System.out.println(flag);
        return flag;


    }

    public static int calculatingAverages(int[] array) {
        int counter=0;
        for(int i=0;i<array.length;i++){
            counter+=array[i];
        }
        System.out.println(counter/array.length);
        return counter/array.length;
    }
    public static int[] lowestAverage(int[][] array) {
        double [] avgArr=new double[array.length];
        for(int i=0;i<array.length;i++){
            int sum=0;
            for(int j=0;j<array[i].length;j++){
                sum+=array[i][j];
            }
            avgArr[i]=sum/array[i].length;
        }
        double min=avgArr[0];
        int index=0;
        for(int k=1;k<avgArr.length;k++){
            if(avgArr[k]<min){
                min=avgArr[k];
                index=k;
            }
        }
        return array[index];
    }
    public static Set<String>  analyzingWeather(int[][] data){
        int minTem=0;
        int maxTem=0;
        Set<Integer> weatherData=new HashSet<>();
        for (int i=0;i<data.length;i++){
            for (int j=0;j<data[i].length;j++){
                weatherData.add(data[i][j]); }
        }
       for (Integer i:weatherData){
           if(maxTem<i){
             maxTem=i; }
           if(minTem>i){
            minTem=i; }
       }
      Set <String> unseenTemp=new HashSet<>();
      for (int k=51;k<72;k++) {
        if(!weatherData.contains(k)){
            unseenTemp.add(String.valueOf(k));
        }
      }
      return unseenTemp;
    }
public static HashMap<String, Integer> tally(List<String> data){
       Integer numberOfVotes=1;
    HashMap<String, Integer> votes= new HashMap<String, Integer>();
    for(String item :data){
        if(votes.containsKey(item)){
            votes.put(item, votes.get(item)+1);
            System.out.println(item);
        }
        else{
            votes.put(item,1);
        }
    }
}
}