/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static int[] roll(int n) {
        int random = (int) (Math.random() * (6 - 1 + 1) + 1);
        int[] rollingResults=new int[n];
        for (int i = 0; i < n; i++) {
            rollingResults[i]=random;
            System.out.println(rollingResults[i]);
            random = (int) (Math.random() * (6 - 1 + 1) + 1);
        }
        return rollingResults;
    }
    public static boolean  containsDuplicates(int[] array){
        boolean flag = false;
        for(int i = 0; i < array.length; i++){
            for(int j = i+1; j < array.length; j++){
                if (array[j] == array[i]){
                    flag = true;
                    System.out.println(flag);
                    return flag;
                }
            }
        }
        System.out.println(flag);
        return flag;


    }

    public static int calculatingAverages(int[] array) {
        int counter=0;
        for(int i=0;i<array.length;i++){
            counter+=array[i];
        }
        System.out.println(counter/array.length);
        return counter;
    }
    public static int[] lowestAverage(int[][] array) {
        double [] avgArr=new double[array.length];
        for(int i=0;i<array.length;i++){
            int sum=0;
            for(int j=0;j<array[i].length;j++){
                sum+=array[i][j];
            }
            avgArr[i]=sum/array[i].length;
        }
        double min=avgArr[0];
        int index=0;
        for(int k=1;k<avgArr.length;k++){
            if(avgArr[k]<min){
                min=avgArr[k];
                index=k;
            }
        }
        return array[index];
    }
}