/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

public class App {

    public static void main(String[] args) {
        String path="resources/gates.js";
        String path1="resources/oneError.js";
        String path2="resources/noerror.js";
        String path3="resources/empty.js";
        System.out.println("many errors ");
  linter(path);
        System.out.println("one error ");
        linter(path1);
        System.out.println("no error");
        linter(path2);
        System.out.println("empty");
        linter(path3);
    }

    public static void linter(String filePath) {
        int counter=1;
        BufferedReader reader ;
        Path path = Paths.get(filePath);
try{
            reader = Files.newBufferedReader(path);
            String line = reader.readLine();
            while(line != null) {
                try {
                    if (line.endsWith(";") || line.endsWith("{") || line.endsWith("}") || line.equals("") || line.contains("if") || line.contains("else")) {

                        counter++;
                        line = reader.readLine();
                    } else {

                        throw new Exception("Line "+counter+": Missing semicolon.");
                    }

                } catch (Exception ex) {

                    System.out.println(ex);
                    counter++;
                    line = reader.readLine();
//        }
                }
            }
        }catch (IOException ex){
    System.out.println(ex.getCause());
}
    }

}